### ISSUE TITLE
[revocation] Implement CRL support

### ISSUE THREAD

**Issue by priteshbandi** [notaryproject/notation-core-go#125]
Spec: https://github.com/notaryproject/notaryproject/blob/main/specs/trust-store-trust-policy.md#crls

Note: For start we can Indirect CRL and can be implemented as step 2.

**Comment by yizha1** [comment]
@priteshbandi  Do you have any plan on implementing CRL checks?

**Comment by JeyJeyGao** [comment]
As we discussed in https://github.com/notaryproject/notation-go/issues/425. We will include the following CRL features for notation **v1.3.0**:
1. **Basic CRL support**  : This includes `base CRL` downloading and validation, with a fallback rule to automatically choose OCSP and fallback to CRL.
2. **CRL cache support**  : Since CRL is a static file with relatively long-term validity, and a well-known CA's CRL is usually greater than 600KiB, a cache mechanism can significantly improve performance.

**Comment by JeyJeyGao** [comment]
CRL and CRL Cache have been merged. We can close this issue now.
