### ISSUE TITLE
bug: fail to verify COSE signature with extra attributes in the protected header

### ISSUE THREAD

**Issue by shizhMSFT** [notaryproject/notation-core-go#88]
When the COSE signature contains extra attribute keys, which are integers not strings, the code reports error:
```
extendedAttributes key requires string type
```
Those keys should be ignored if not marked as critical, or report error if marked as critical. If they are known attributes, we may convert keys into strings so that it can fill in the `signature.Attribute` structure.

Related code:
https://github.com/notaryproject/notation-core-go/blob/b5df54c7465b0c1b177233108355b4e7314f1a14/signature/cose/envelope.go#L531-L544

**Comment by patrickzheng200** [comment]
I will take this one.

**Comment by priteshbandi** [comment]
> Those keys should be ignored if not marked as critical, or report error if marked as critical.

Can this cause issues if a plugin is expecting those attributes? Also, silently ignoring attributes doesn't look right. Do you have a specific usecase?

> If they are known attributes, we may convert keys into strings so that it can fill in the signature.Attribute structure.

What will we do in case of a collision? IMO unless we have a specific usecase to support, we should continue to fail verification if we encounter non-string keys in signed attributes.

**Comment by patrickzheng200** [comment]
> > Those keys should be ignored if not marked as critical, or report error if marked as critical.
> 
> Can this cause issues if a plugin is expecting those attributes? Also, silently ignoring attributes doesn't look right. Do you have a specific usecase?
> 
> > If they are known attributes, we may convert keys into strings so that it can fill in the signature.Attribute structure.
> 
> What will we do in case of a collision? IMO unless we have a specific usecase to support, we should continue to fail verification if we encounter non-string keys in signed attributes.

Please correct me if I'm wrong, according to our implementation in notation-go [executePlugin](https://github.com/notaryproject/notation-go/blob/e0892fc6008d9e375a3fe4ba01298284bba45f7f/verification/verifier_helpers.go#L261), we are only passing critical extended attributes to plugin.VerifySignatureRequest. In other words, if a plugin expects a certain attribute, it has to be marked as critical anyway.

For COSE envelope, there could be non-string [keys](https://www.iana.org/assignments/cose/cose.xhtml#header-parameters), for example, key of kid is 4. In this case, if it is non-critical, we can ignore it instead of failing the verification. If it's marked critical, we return an error requiring string type. If a plugin expects this extended attribute, then it needs to mark the attribute as critical and has a way to encode/decode non-string type keys inside the plugin.
Finally, there shouldn't be collision issue for a COSE envelope, since [ProtectedHeader](https://github.com/veraison/go-cose/blob/ac30917645090cb2fa087cbf785d01df9c7a5292/headers.go#L31)  is a Map by design.

**Comment by patrickzheng200** [comment]
> > > > Those keys should be ignored if not marked as critical, or report error if marked as critical.
> > > 
> > > 
> > > Can this cause issues if a plugin is expecting those attributes? Also, silently ignoring attributes doesn't look right. Do you have a specific usecase?
> > > > If they are known attributes, we may convert keys into strings so that it can fill in the signature.Attribute structure.
> > > 
> > > 
> > > What will we do in case of a collision? IMO unless we have a specific usecase to support, we should continue to fail verification if we encounter non-string keys in signed attributes.
> > 
> > 
> > Please correct me if I'm wrong, according to our implementation in notation-go [executePlugin](https://github.com/notaryproject/notation-go/blob/e0892fc6008d9e375a3fe4ba01298284bba45f7f/verification/verifier_helpers.go#L261), we are only passing critical extended attributes to plugin.VerifySignatureRequest. In other words, if a plugin expects a certain attribute, it has to be marked as critical anyway.
> > For COSE envelope, there could be non-string [keys](https://www.iana.org/assignments/cose/cose.xhtml#header-parameters), for example, key of kid is 4. In this case, if it is non-critical, we can ignore it instead of failing the verification (one of our users is blocked due to this logic). If it's marked critical, we return an error requiring string type. If a plugin expects this extended attribute, then it needs to mark the attribute as critical for now. Finally, there shouldn't be collision issue for a COSE envelope, since [ProtectedHeader](https://github.com/veraison/go-cose/blob/ac30917645090cb2fa087cbf785d01df9c7a5292/headers.go#L31) is a Map by design. @shizhMSFT @priteshbandi
> 
> Yes, currently we only pass critical attributes to plugin but we don't want to limit it for future usecase.
> 
> In cose both `4 as int` and `4 as string` can co-exist in [ProtectedHeader](https://github.com/veraison/go-cose/blob/ac30917645090cb2fa087cbf785d01df9c7a5292/headers.go#L31) map. If both are marked critical which one will we prefer and why? Signature's generated using notation wont have signed integer keys in [ProtectedHeader](https://github.com/veraison/go-cose/blob/ac30917645090cb2fa087cbf785d01df9c7a5292/headers.go#L31). Do you have a specific usecase that you want to support with ignoring integer values?

So we have 2 scenarios here:
1. Critical extended attributes require keys of string type. -> In case of `4 as int` and marked as critical mentioned in your comment, we would fail the verification. And therefore, this kind of collision will not happen.
2. Non-critical extended attributes with non-string type keys will be ignored. -> This is solving one of our use case, where it is failed because it has x5t (`34 as int`) in COSE's extended attribute. (This Signature is not generated using Notation.) And we don't want to fail the verification directly in this scenario.

For Notation, my understanding is that Sign and Verification are two separated operations. One can generate his own COSE Envelope somewhere else and use Notation to Verify it. Hence, I think we should accept a more general form of Signature Envelope like the one I mentioned above.

**Comment by patrickzheng200** [comment]
@rgnote @priteshbandi Any further comments/concerns on this one?

**Comment by rgnote** [comment]
> Non-critical extended attributes with non-string type keys will be ignored. -> This is solving one of our use cases, where it is failed because it has x5t (34 as int) in COSE's extended attribute. (This Signature is not generated using Notation.) And we don't want to fail the verification directly in this scenario.

Ignoring keys silently doesn't seem the right approach here. It is a one-way door decision where notation will never be able to enforce string keys for non-critical extended attributes in the future. I agree that users should be able to verify signatures that are generated outside notation, but that doesn't mean notation allows verification of signatures that don't follow the notation guidelines. We should keep signatures restricted to what types notation is expecting today so that we can loosen these restrictions when we see new usecases (as opposed to the other way around) 

That being said, can you explain your usecase where x5t (`34 as int`) can't be marked as string?

**Comment by patrickzheng200** [comment]
> That being said, can you explain your usecase where x5t (`34 as int`) can't be marked as string?

It's because the [COSE Header Parameters](https://www.iana.org/assignments/cose/cose.xhtml#header-parameters) regulates the label type of a COSE header, from which it can be string or integer. In other words, if we claim to support COSE format, then we need to follow the COSE standard. 
After a discussion with @shizhMSFT, we propose another option here to avoid ignoring keys silently. We can change the [key type](https://github.com/notaryproject/notation-core-go/blob/56bd40a80d26eb280e388bf96d3f1b41fe766045/signature/types.go#L56) of Attribute from string to interface{}. Note, JWS format will still enforce extended attribute keys as string type. This change will NOT touch JWS. 
In case of the above-mentioned concern regarding collision when `4 as int` and `4 as string` both exist, we don't think it's a collision. Because we never do type conversion on keys, i.e. `4 as int` and `4 as string` are just two independent keys. 
For more details, please take a look at PR #89. @rgnote @priteshbandi

**Comment by rgnote** [comment]
LGTM

**Comment by rgnote** [comment]
Reopening as this is causing an issue with verification plugins. 

See https://github.com/notaryproject/notaryproject/blob/main/specs/plugin-extensibility.md#verify-signature-command

As part of `criticalAttributes`, the Verifier needs to send extended critical attributes to the verification plugin. That means, we will need to covert types of attributes to `string` (`encoding/json` doesn't support `interface{}` keys). That also means, attribute collisions (`4 as int` and `4 as string`) are possible.

**Comment by shizhMSFT** [comment]
@rgnote In the spec you've pointed, `unprocessedAttributes` is an array of names of critical attributes that plugin. Since it is an array not a map, it can accept any type of keys although the spec is not well defined.

**Comment by rgnote** [comment]
@shizhMSFT The issue is around `extendedAttributes` not `unprocessedAttributes`

**Comment by rgnote** [comment]
I raised [this PR](https://github.com/notaryproject/notation-go/pull/188/files) to unblock JWS signatures. Please raise a PR for spec updates once you have an idea on how verification plugins needs to deal with COSE extended attributes

**Comment by shizhMSFT** [comment]
Closed by https://github.com/notaryproject/notation-go/pull/188 and will follow up https://github.com/notaryproject/notaryproject/issues/201
